//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SubmissionEvaluation.Domain.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SubmissionEvaluation.Domain.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Erweiterte Fehlermeldung: {0}
        /// ähnelt.
        /// </summary>
        internal static string EvaluationMessages_BodyErrorMessage {
            get {
                return ResourceManager.GetString("EvaluationMessages_BodyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tipp ähnelt.
        /// </summary>
        internal static string EvaluationMessages_BodyHint {
            get {
                return ResourceManager.GetString("EvaluationMessages_BodyHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die 
        ///Viele Grüße
        ///
        ///Das Challenges-Team
        ///
        ///---
        ///
        ///Test fehlgeschlagen? Du brauchst Hilfe? Versuch es hier:
        ///{0}/help/index.html
        ///
        ///Weitere Details zu den verwendeten Compilerversionen können hier abgerufen werden:
        ///{0}/compilers/index.html
        ///
        ///Für alle weiteren Fragen, einfach eine Mail senden an:
        ///{1}
        /// ähnelt.
        /// </summary>
        internal static string MailMessages_Footer {
            get {
                return ResourceManager.GetString("MailMessages_Footer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo {0},
        ///
        ///du warst seit 6 Monaten nicht mehr im Challenges Portal aktiv.
        ///
        ///Wie wäre es mit einer neuen Herausforderung?
        ///
        ///{1}
        ///{2}
        ///
        ///
        ///Dein Status wurde auf inaktiv gesetzt. Du wirst keine weiteren Mails oder Review Anfragen erhalten, bis du wieder im Challenges Portal aktiv wirst.
        /// ähnelt.
        /// </summary>
        internal static string MailMessages_InactivityReminderChallengeRecommendation {
            get {
                return ResourceManager.GetString("MailMessages_InactivityReminderChallengeRecommendation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo {0},
        ///
        ///du warst seit 6 Monaten nicht mehr im Challenges Portal aktiv.
        ///
        ///Du hast noch ungelöste Challenges, die du erneut einreichen könntest.
        ///
        ///{1}
        ///{2}
        ///
        ///
        ///Dein Status wurde auf inaktiv gesetzt. Du wirst keine weiteren Mails oder Review Anfragen erhalten, bis du wieder im Challenges Portal aktiv wirst.
        /// ähnelt.
        /// </summary>
        internal static string MailMessages_InactivityReminderUnsolvedChallenge {
            get {
                return ResourceManager.GetString("MailMessages_InactivityReminderUnsolvedChallenge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hallo {0},
        ///
        ///Du wurdest für ein Code Review ausgewählt (Codegröße {2} Bytes). Bitte reviewe die Einreichung innerhalb von {3} Tagen. Falls Du derzeit keine Lust oder Zeit hast, einfach die Mail ignorieren. Wird innerhalb der Frist kein Reviewergebnis eingereicht, so wird jemand anderes um das Review gebeten.
        ///
        ///Das Review kannst du auf der Seite hier durchführen:
        ///{4}
        ///
        ///Mitarbeiter können die für das Review benötigte Zeit auf das 150h Budget für Schulung/Weiterbildung buchen. Studenten können das einfach  [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        /// </summary>
        internal static string MailMessages_ReviewBody {
            get {
                return ResourceManager.GetString("MailMessages_ReviewBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Anfrage für ein Code Review ({0} /{1}) ähnelt.
        /// </summary>
        internal static string MailMessages_ReviewHeader {
            get {
                return ResourceManager.GetString("MailMessages_ReviewHeader", resourceCulture);
            }
        }
    }
}
